services:
    _defaults:
        autowire: false #change to true
        autoconfigure: false
        public: true #because controller

    # Authenticators
    Claroline\AuthenticationBundle\Security\Authentication\IpAuthenticator:
        calls:
            - method: inject
              arguments:
                  - '@Claroline\CoreBundle\Library\Configuration\PlatformConfigurationHandler'
                  - '@claroline.manager.ip_white_list_manager'

    Claroline\AuthenticationBundle\Security\Authentication\ApiTokenAuthenticator:
        calls:
            - method: inject
              arguments:
                  - '@Claroline\AppBundle\Persistence\ObjectManager'

    # SAML
    Claroline\AuthenticationBundle\Security\Saml\EntityDescriptorProvider:
        #factory: ['LightSaml\SymfonyBridgeBundle\Factory\OwnEntityDescriptorProviderFactory', 'build']
        arguments:
            - '%lightsaml.own.entity_id%'
            - '@router'
            - '%lightsaml.route.login_check%'
            - '@lightsaml.own.credential_store'

    Claroline\AuthenticationBundle\Security\Saml\Store\IdStore:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@lightsaml.system.time_provider'

    Claroline\AuthenticationBundle\Security\Saml\Store\RequestStateStore:
        arguments:
            - '@doctrine.orm.entity_manager'

    Claroline\AuthenticationBundle\Security\Saml\UserCreator:
        arguments:
            - '%secret%'
            - '@security.token_storage'
            - '@lightsaml_sp.username_mapper.simple'
            - '@Claroline\AppBundle\API\Crud'

    Claroline\AuthenticationBundle\Security\Saml\LogoutHandler:
        calls:
            - [setContainer, ['@service_container']]

    # OAuth
    Claroline\AuthenticationBundle\Security\Oauth\Hwi\ResourceOwnerFactory:
        arguments:
            - '@Claroline\AuthenticationBundle\Manager\OauthManager'
            - '@security.http_utils'
            - '@session'

    Claroline\AuthenticationBundle\Security\Oauth\AuthenticationFailureHandler:
        arguments:
            - '@router'
            - '@translator'

    Claroline\AuthenticationBundle\Security\Oauth\LogoutHandler:
        arguments:
            - '@session'
            - '@Claroline\AuthenticationBundle\Security\Oauth\Hwi\ResourceOwnerFactory'

    Claroline\AuthenticationBundle\Security\Oauth\OauthUserProvider:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@session'
            - '@Claroline\CoreBundle\Library\Configuration\PlatformConfigurationHandler'
